# Project
version=1.21.4-1.0.4
group=com.graclyxz.shortswords

# Mod options
mod_name=Short Swords
mod_author=Graclyxz
mod_id=shortswords
mod_license=MIT License
mod_description=dds new short swords that can be craftable with a single ore, \nthey are faster than the vanilla version but have one point less damage.
mod_url=https://www.curseforge.com/minecraft/mc-mods/shortswords
mod_issues=https://github.com/Graclyxz/ShortsSwords/issues

# Common
minecraft_version=1.21.4

# Forge
forge_version=1.21.4-54.0.1
forge_version_range=[54.0.1,)
forge_loader_version_range=[54,)
forge_minecraft_version_range=[1.21.4,1.22)
forge_side=BOTH

# NeoForge
neoforge_version=21.4.2-beta
neoforge_version_range=[21.4.0-beta,)
neoforge_loader_version_range=[1,)
neoforge_minecraft_version_range=[1.21.4,1.22)
neoforge_side=BOTH

# Fabric
fabric_api_version=0.110.5+1.21.4
fabric_loader_version=0.16.7
fabric_loader_version_range=>=0.15.0
fabric_minecraft_version_range=>=1.21.4 <1.22
fabric_side=*

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false